### PR TITLE
#161780550- Integrate Travis CI with readme badge

### PR DESCRIPTION
**Pull request by Bobjayafam**
#### Description
When Engineers work on a feature without continuous integration, there is a likelihood the pushed code will break the application. With TravisCI setup, checks before merging with the codebase will ensure the code passes automated tests thereby reducing risks of introducing bugs into the codebase.
#### Type of change
Chore: add a .travis.yml file with configurations for a node/Postgres app and add a readme badge.
#### Pivotal Tracker ID
#161780550

### CODE REVIEW

**Comment by fuchodeveloper** [comment]
Add a simple test to confirm implementation

**Comment by Bobjayafam** [comment]
Ok thanks, I will work on that.

**Comment by Fiyiin** [comment]
Looks good

**Comment by Joyce-O** [comment]
Looks  good

**Comment by kossy360** [comment]
LGTM

**Comment by fuchodeveloper** [comment]
Remove implementations not related to integrating Travis

**Comment by fuchodeveloper** [comment]
Looks good

**Pull request merged**
