### PR TITLE
#161780557 create base API documentation with swagger

### PR DESCRIPTION
**Pull request by Jesse-efe**
#### Description
A base API documentation was created with the login endpoint

#### Type of change
Documentation

#### How Has This Been Tested?
N/A

#### Checklist:
N/A

#### Pivotal tracker id
#161780557

### CODE REVIEW

**Comment by innocentEdosa** [comment]
Hello jesse-efe 
please, why do we have twenty files changed?

**Comment by Jesse-efe** [comment]
> Hello jesse-efe
> please, why do we have twenty files changed?

this files came with the swagger-ui and swagger-ui-dist modules

**Review by fuchodeveloper — COMMENTED** [review]
double check on the file changes to know the ones that need to be ignore on the repo

**Comment by Jesse-efe** [comment]
ok I will

**Pull request merged**
