### PR TITLE
#161780555 Setup unit testing

### PR DESCRIPTION
**Pull request by innocentEdosa**
#### Description
This PR sets up unit testing so that all backend functionality is tested to show if they work as intended

#### Type of change

Installs mocha, chai, chai-http, sinon
creates a test folder
creates a test file
writes a test script in the package.json file

#### Pivotal tracker id
#161780555

### CODE REVIEW

**Comment by fuchodeveloper** [comment]
Resolve merge conflicts

**Comment by innocentEdosa** [comment]
Conflicts have been resolved.

**Comment by Bobjayafam** [comment]
LGTM

**Comment by Fiyiin** [comment]
LGTM

**Comment by fuchodeveloper** [comment]
Looks good

**Pull request merged**
