### PR TITLE
161780582 Adds highlight and comment feature

### PR DESCRIPTION
**Pull request by kayroy247**
**Description**
- Adds Highlight and comment functionality

**Type of Change**
- Feature

**Flow Chart**
image

**Pivotal Tracker ID**
161780582

### CODE REVIEW

**Comment by Bobjayafam** [comment]
LGTM

**Review by innocentEdosa — COMMENTED** [review]
Good job Joyce, kay and Jesse
However, using JSdocs makes it easier for any other member of the team to understand your code especially if they are to work with it. 
https://en.wikipedia.org/wiki/JSDoc

You may want to use JSdocs for those function where u did not.
Thanks

**Comment by Jesse-efe** [comment]
ok

**Comment by innocentEdosa** [comment]
LGTM

**Pull request merged**
